FROM confluentinc/cp-kafka-connect
COPY debezium-connector-postgres /usr/share/java/debezium-connector-postgres/
COPY confluentinc-kafka-connect-elasticsearch/lib/ /usr/share/java/confluentinc-kafka-connect-elasticsearch/
